cdms/urls.py
from django.conf.urls import url
from . import views

app_name = 'cdms'

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^most_wanted/$', views.most_wanted, name='most_wanted'),
	url(r'^wanted/$', views.wanted, name='wanted'),
	url(r'^add_criminal/$', views.add_criminal, name='add_criminal'),
	url(r'^search/$', views.search_criminal, name='search_criminal'),
	url(r'^train/$', views.train, name='train'),
	url(r'^(?P<criminal_id>[0-9]+)/$', views.criminal_details, name='criminal_details'),
	url(r'^v(?P<criminal_id>[0-9]+)/$', views.criminal_details2, name='criminal_details2'),
	url(r'^(?P<criminal_id>[0-9]+)/update/$', views.update_criminal, name='update_criminal'),
	url(r'^(?P<criminal_id>[0-9]+)/add_images/$', views.add_images, name='add_images'),
	url(r'^(?P<criminal_id>[0-9]+)/image/(?P<criminal_images_id>[0-9]+)/delete/$', views.delete_image, name='delete_image'),
	url(r'^(?P<criminal_id>[0-9]+)/delete/$', views.delete_criminal, name='delete_criminal'),
	url(r'^get_thanas/(?P<district_id>[0-9]+)/$', views.get_thanas, name='get_thanas'),
	url(r'^add_district/$', views.add_district, name='add_district'),
	url(r'^districts/$', views.district_list, name="district_list"),
	url(r'^districts/(?P<district_id>[0-9]+)/update/$', views.update_district, name='update_district'),
	url(r'^add_thana/$', views.add_thana, name='add_thana'),
	url(r'^thana_list/$', views.thana_list, name="thana_list"),
	url(r'^thana/(?P<thana_id>[0-9]+)/update/$', views.update_thana, name='update_thana'),
	url(r'^dashboard/$', views.dashboard, name='dashboard'),
	url(r'^search_thana/$', views.search_thana, name='search_thana'),
	url(r'^gd_form/$', views.gd_form, name='gd_form'),
	url(r'^gd_list/$', views.gd_list, name='gd_list'),
	url(r'^gd_details/(?P<gd_id>[0-9]+)/$', views.gd_details, name='gd_details'),
	url(r'^admin_list/$', views.admin_list, name='admin_list'),
	url(r'^add_admin/$', views.add_admin, name='add_admin'),
	url(r'^admin_details/(?P<user_id>[0-9]+)/$', views.admin_details, name='admin_details'),
	url(r'^admin_details/(?P<user_id>[0-9]+)/update/$', views.update_admin, name='update_admin'),
	url(r'^admin_details/(?P<user_id>[0-9]+)/(?P<type>\w+)/toggle_user_state/$', views.toggle_user_state, name='toggle_user_state'),
	url(r'^admin_details/(?P<user_id>[0-9]+)/toggle_admin_state/$', views.toggle_admin_state, name='toggle_admin_state'),
	url(r'^officer_list/$', views.officer_list, name='officer_list'),
	url(r'^officer_list_admin/$', views.officer_list_admin, name='officer_list_admin'),
	url(r'^officer_list_reserve/$', views.officer_list_reserve, name='officer_list_reserve'),
	url(r'^add_officer/$', views.add_officer, name='add_officer'),
	url(r'^officer_details/(?P<user_id>[0-9]+)/$', views.officer_details, name='officer_details'),
	url(r'^officer_details/(?P<user_id>[0-9]+)/update/$', views.update_officer, name='update_officer'),
	url(r'^thana_details/(?P<thana_id>[0-9]+)/$', views.thana_details, name='thana_details'),
	url(r'^appoint_officer/(?P<thana_id>[0-9]+)/$', views.appoint_officer, name='appoint_officer'),
	url(r'^appoint_oc/(?P<thana_id>[0-9]+)/$', views.appoint_oc, name='appoint_oc'),
	url(r'^remove_officer/(?P<user_id>[0-9]+)/(?P<thana_id>[0-9]+)/$', views.remove_officer, name='remove_officer'),
	url(r'^login/$', views.login_user, name='login'),
	url(r'^logout/$', views.logout_user, name='logout'),
	url(r'^assign_action_officer/(?P<gd_id>[0-9]+)/$', views.assign_action_officer, name='assign_action_officer'),
	url(r'^remove_action_officer/(?P<gd_id>[0-9]+)/$', views.remove_action_officer, name='remove_action_officer'),
	url(r'^gd_action/(?P<gd_id>[0-9]+)/$', views.gd_action, name='gd_action'),
	url(r'^fir_form/$', views.fir_form, name='fir_form'),
	url(r'^print_fir/(?P<case_id>[0-9]+)/$', views.print_fir, name='print_fir'),
	url(r'^case_details/(?P<case_id>[0-9]+)/$', views.case_details, name='case_details'),
	url(r'^case_list/$', views.case_list, name='case_list'),
	url(r'^case_investigation_officers/(?P<case_id>[0-9]+)/$', views.case_investigation_officers, name='case_investigation_officers'),
	url(r'^assign_investigation_officer/(?P<case_id>[0-9]+)/$', views.assign_investigation_officer, name='assign_investigation_officer'),
	url(r'^close_form_case/(?P<officer_id>[0-9]+)/$', views.close_form_case, name='close_form_case'),
	url(r'^case_updates/(?P<case_id>[0-9]+)/$', views.case_updates, name='case_updates'),
	url(r'^case_update_form/(?P<case_id>[0-9]+)/$', views.case_update_form, name='case_update_form'),
	url(r'^charge_sheet/(?P<case_id>[0-9]+)/$', views.charge_sheet, name='charge_sheet'),
	url(r'^add_charge_sheet/(?P<case_id>[0-9]+)/$', views.add_charge_sheet, name='add_charge_sheet'),
	url(r'^case_verdict/(?P<case_id>[0-9]+)/$', views.case_verdict, name='case_verdict'),
	url(r'^add_case_verdict/(?P<case_id>[0-9]+)/$', views.add_case_verdict, name='add_case_verdict'),
	url(r'^case_transfer/(?P<case_id>[0-9]+)/$', views.case_transfer, name='case_transfer'),
	url(r'^profile/$', views.profile, name='profile'),
	url(r'^change_password/$', views.change_password, name='change_password'),
	url(r'^toggle_case_state/(?P<case_id>[0-9]+)/$', views.toggle_case_state, name='toggle_case_state'),
	url(r'^print_gd/(?P<gd_id>[0-9]+)/$', views.print_gd, name='print_gd'),
	url(r'^criminal_fir_list/(?P<criminal_id>[0-9]+)/$', views.criminal_fir_list, name='criminal_fir_list'),
]

cse/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^cdms/', include('cdms.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cdms/models.py
from __future__ import unicode_literals
from uuid import uuid4
import os
from django.db import models
from .choices import *
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.utils.deconstruct import deconstructible
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


@deconstructible
class PathAndRename(object):

    def __init__(self, sub_path, model_name):
		self.path = sub_path
		self.model_name = model_name
		
    def __call__(self, instance, filename):
		ext = filename.split('.')[-1]
		complaint_id = "%s" %  (getattr(instance, self.model_name).pk)
		random_id = "%s" % (uuid4().hex,)
		filename = '{}.{}.{}'.format(complaint_id, random_id, ext)
		return os.path.join(self.path, filename)

path_and_rename = PathAndRename("raw", "criminal")

path_and_rename_for_pro_pics = PathAndRename("pro_pics", "user")

@deconstructible
class PathAndRenameForGD(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
		ext = filename.split('.')[-1]
		lastIndexOfDot = filename.rindex('.')
		orgName = filename[:lastIndexOfDot]
		gd_id = "%s" % (instance.gd.pk,)
		random_id = "%s" % (uuid4().hex,)
		filename = '{}.{}.{}.{}'.format(gd_id, orgName, random_id, ext)
		return os.path.join(self.path, filename)

path_and_rename_for_gd = PathAndRenameForGD("gd_files")

@deconstructible
class PathAndRenameForCase(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
		ext = filename.split('.')[-1]
		lastIndexOfDot = filename.rindex('.')
		orgName = filename[:lastIndexOfDot]
		gd_id = "%s" % (instance.case.pk,)
		random_id = "%s" % (uuid4().hex,)
		filename = '{}.{}.{}.{}'.format(gd_id, orgName, random_id, ext)
		return os.path.join(self.path, filename)

path_and_rename_for_case = PathAndRenameForCase("case_files")

@deconstructible
class PathAndRenameForCaseUpdate(object):

    def __init__(self, sub_path):
        self.path = sub_path

    def __call__(self, instance, filename):
		ext = filename.split('.')[-1]
		lastIndexOfDot = filename.rindex('.')
		orgName = filename[:lastIndexOfDot]
		gd_id = "%s" % (instance.case_update.pk,)
		random_id = "%s" % (uuid4().hex,)
		filename = '{}.{}.{}.{}'.format(gd_id, orgName, random_id, ext)
		return os.path.join(self.path, filename)

path_and_rename_for_case_update = PathAndRenameForCaseUpdate("case_files")



class District(models.Model):
	name = models.CharField(max_length = 100)
	
	def __str__(self):
		return self.name
	
class Thana(models.Model):
	district = models.ForeignKey(District)
	name = models.CharField(max_length = 250)
	mobile = models.CharField(max_length = 50, null = True, blank = True)
	email = models.CharField(max_length = 200, null = True, blank = True)
	address = models.TextField(null = True, blank = True)
	
	def __str__(self):
		return self.name

class Criminal(models.Model):
	criminal_id = models.CharField(max_length = 100)
	criminal_status = models.CharField(max_length = 10, choices=CRIMINAL_STATUS, blank = True)
	district = models.ForeignKey(District)
	thana = models.ForeignKey(Thana)
	name = models.CharField(max_length = 250)
	aliases = models.CharField(max_length = 1000, blank = True)
	dob = models.DateField("Date of Birth", null = True, blank = True)
	birth_place = models.CharField(max_length = 100, null = True, blank = True)
	father_name = models.CharField(max_length = 200, null = True, blank = True)
	mother_name = models.CharField(max_length = 200, null = True, blank = True)
	present_address = models.CharField(max_length = 300, null = True, blank = True)
	permanent_address = models.CharField(max_length = 300, null = True, blank = True)
	hair = models.CharField(max_length = 100, blank = True)
	eyes = models.CharField(max_length = 100, blank = True)
	height = models.CharField(max_length = 50, blank = True)
	weight = models.CharField(max_length = 50, blank = True)
	gender = models.CharField(max_length = 10, choices=GENDER, blank = True)
	race = models.CharField(max_length = 50, blank = True)
	scars_and_marks = models.CharField(max_length = 300, blank = True)
	nationality = models.CharField(max_length = 50, blank = True)
	crime_titles = models.CharField(max_length = 1000, blank = True)
	description = models.TextField(blank = True)
	rewards = models.CharField(max_length = 1000, blank = True)
	remarks = models.TextField(blank = True)
	cautions = models.CharField(max_length = 500, blank = True)
	
	def __str__(self):
		return self.criminal_id + ' - ' + self.name
		
class Criminal_images(models.Model):
	criminal = models.ForeignKey(Criminal, on_delete = models.CASCADE)
	image = models.ImageField(upload_to=path_and_rename)
	face = models.ImageField(upload_to='faces', null = True, blank = True)
	
class TempImages(models.Model):
	image = models.ImageField(upload_to='temps')

class Criminal_fir_list(models.Model):
	criminal = models.ForeignKey(Criminal, on_delete = models.CASCADE)
	fir_number = models.CharField(max_length = 100)
	fir_id = models.CharField(max_length = 100, null = True)

class GeneralDiary(models.Model):
	district = models.ForeignKey(District)
	thana = models.ForeignKey(Thana)
	name = models.CharField(max_length = 100)
	father_name = models.CharField("Father's Name",max_length = 100, blank = True)
	mother_name = models.CharField("Mother's Name", max_length = 100, blank = True)
	present_address = models.CharField(max_length = 300, blank = True)
	permanent_address = models.CharField(max_length = 300, blank = True)
	national_id = models.CharField(max_length = 100, blank = True)
	mobile = models.CharField(max_length = 50, blank = True)
	email = models.CharField(max_length = 150, blank = True)
	description = models.TextField()
	date_time = models.DateTimeField()
	seen_by_sup = models.BooleanField(default=False)
	seen_by_sub = models.BooleanField(default=False)
	assigned_by = models.ForeignKey(User, related_name='+', blank = True, null = True)
	action_officer = models.ForeignKey(User, related_name='+', blank = True, null = True)
	action_details = models.TextField(blank = True)
	is_action_taken = models.BooleanField(default=False)
	
class GD_files(models.Model):
	gd = models.ForeignKey(GeneralDiary, on_delete = models.CASCADE)
	file = models.FileField(upload_to=path_and_rename_for_gd)


	
class Officer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	rank = models.CharField(max_length = 10, choices=RANK)
	position = models.CharField(max_length = 100, null = True, blank = True)
	officer_id = models.CharField(max_length = 50, blank = True)
	area = models.CharField(max_length = 300, null = True, blank = True)
	district = models.ForeignKey(District, null=True, blank = True)
	thana = models.ForeignKey(Thana, null=True, blank = True)
	admin_type = models.CharField(max_length = 10, choices=ADMIN_TYPE, null=True, blank = True)
	officer_type = models.CharField(max_length = 10, choices=OFFICER_TYPE, default='R')
	mobile = models.CharField("Mobile numbers", max_length = 50, blank = True)
	pro_pic = models.ImageField("Profile picture", upload_to=path_and_rename_for_pro_pics, null = True, blank = True)

	def __str__(self):
		return self.user.get_full_name()
		
	def is_level_1(self):
		if self.admin_type == 'S':
			return True
		else:
			return False
	
	def is_level_2(self):
		if self.admin_type == 'S' or self.admin_type == 'A':
			return True
		else:
			return False
			
	def is_level_3(self, thana_id=None, district_id=None):
		if self.admin_type == 'OC' or (self.officer_type == 'C' and not (self.rank == 'I' or self.rank == 'SI' or self.rank == 'ASI' )):
			if thana_id is not None and self.thana is not None:
				if self.thana.id == thana_id:
					return True
				else:
					return False
			if district_id is not None and self.district is not None:
				if self.district.id == district_id:
					return True
				else:
					return False
			return True
		else:
			return False
			
	def is_level_4(self, thana_id=None):
		if self.officer_type == 'C' and not self.admin_type == 'OC' and (self.rank == 'I' or self.rank == 'SI' or self.rank == 'ASI' ):
			if thana_id is not None and self.thana is not None:
				if self.thana.id == thana_id:
					return True
				else:
					return False
			return True
		else:
			return False
	
@receiver(post_delete, sender=Criminal_images)
def photo_post_delete_handler(sender, **kwargs):
	photo = kwargs['instance']
	storage, path = photo.image.storage, photo.image.path
	storage.delete(path)
	if photo.face:
		storage, path = photo.face.storage, photo.face.path
		storage.delete(path)


class Case(models.Model):
	district = models.ForeignKey(District)
	thana = models.ForeignKey(Thana)
	fir_number = models.CharField("FIR number", max_length = 100)
	section = models.CharField("Section of a rule", max_length = 300)
	date_time = models.DateTimeField(auto_now_add=True)
	duty_officer = models.ForeignKey(User)
	location = models.CharField("Location and Distance", max_length = 300, null=True)
	description = models.TextField()
	reason = models.CharField("Why late to file a FIR", max_length = 300, null=True,blank=True)
	seen_by_sup = models.BooleanField(default=False)
	seen_by_sub = models.BooleanField(default=False)
	case_closed = models.BooleanField(default=False)

class Case_FIR_Files(models.Model):
	case = models.ForeignKey(Case, on_delete = models.CASCADE)
	file = models.FileField(upload_to=path_and_rename_for_case)
		
class Complainant(models.Model):
	case = models.OneToOneField(Case, on_delete = models.CASCADE)
	name = models.CharField(max_length = 100)
	father_name = models.CharField("Father's Name",max_length = 100, blank = True)
	mother_name = models.CharField("Mother's Name", max_length = 100, blank = True)
	present_address = models.CharField(max_length = 300, blank = True)
	permanent_address = models.CharField(max_length = 300, blank = True)

cdms/templates/cdms/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}CIES{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'cdms/images/fav.png' %}"/>
    <link rel="stylesheet" href="{% static 'cdms/bootstrap-3.3.7/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'cdms/css/font-awesome.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'cdms/style.css' %}"/>
	{% block forCSS %}
	{% endblock %}
	
    <script src="{% static 'cdms/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'cdms/bootstrap-3.3.7/js/bootstrap.min.js' %}"></script>

</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu-content">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'cdms:dashboard' %}">Crime Investigation Enhancement System</a>
			
        </div>
		<div class="dropdown pull-right">
			<button class="btn dropdown-toggle user-dropdown-menu-btn" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
				{% if user.officer.pro_pic %}
					<img class="img-circle" src="{{ user.officer.pro_pic.url }}" alt="Profile Picture" height="24" width="24">
				{% else %}
					<i class="fa fa-user fa-lg"></i>
				{% endif %}
				{{ user.username }} 
				<span class="caret"></span>
			</button>
			<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				<li><a href="{% url 'cdms:profile' %}">Profile</a></li>
				<li><a href="{% url 'cdms:change_password' %}">Change password</a></li>
				<li role="separator" class="divider"></li>
				<li><a href="{% url 'cdms:logout' %}">Log out</a></li>
			</ul>
		</div>
		<div class="nav-side-menu">
			<div class="menu-list">
	  
				<ul id="menu-content" class="menu-content collapse out">
					<li class="{% block active-home %}{% endblock %}">
					  <a href="{% url 'cdms:dashboard' %}">
					  <i class="fa fa-home fa-lg"></i> Home
					  </a>
					</li>

					<li  data-toggle="collapse" data-target="#criminal" class="collapsed {% block active-criminal %}{% endblock %}">
					  <a href="#"><i class="fa fa-gift fa-lg"></i> Criminal records <span class="arrow"></span></a>
					</li>
					<ul class="sub-menu collapse" id="criminal">
						{% if user.officer.is_level_3 %}
						<li class="{% block active-add-new %}{% endblock %}"><a href="{% url 'cdms:add_criminal' %}">Add new</a></li>
						{% endif %}
						<li class="{% block active-search %}{% endblock %}"><a href="{% url 'cdms:search_criminal' %}">Search</a></li>
						{% if user.officer.is_level_3 %}
						<li><a href="{% url 'cdms:train' %}">Train Image Data</a></li>
						{% endif %}
					</ul>
					{% if user.officer.is_level_2 %}
					<li  data-toggle="collapse" data-target="#admin" class="collapsed {% block active-admin %}{% endblock %}">
					  <a href="#"><i class="fa fa-gift fa-lg"></i> Admin <span class="arrow"></span></a>
					</li>
					<ul class="sub-menu collapse" id="admin">
						{% if user.officer.is_level_1 %}
						<li class="{% block active-admin-list %}{% endblock %}"><a href="{% url 'cdms:admin_list' %}">Administrators</a></li>
						{% endif %}
						<li class="{% block active-officer-list %}{% endblock %}"><a href="{% url 'cdms:officer_list' %}">Officers</a></li>
					</ul>
					{% endif %}
					</li>
					<li  data-toggle="collapse" data-target="#thana" class="collapsed {% block active-thana %}{% endblock %}">
					  <a href="#"><i class="fa fa-building fa-lg"></i> Thana <span class="arrow"></span></a>
					</li>
					<ul class="sub-menu collapse" id="thana">
						{% if user.officer.is_level_2 %}
						<li class="{% block active-add-thana %}{% endblock %}"><a href="{% url 'cdms:add_thana' %}">Add new</a></li>
						{% endif %}
						<li class="{% block active-thana-list %}{% endblock %}"><a href="{% url 'cdms:thana_list' %}">Thana List</a></li>
						{% if user.officer.is_level_2 %}
						<li class="{% block active-districts %}{% endblock %}"><a href="{% url 'cdms:district_list' %}">Districts</a></li>
						{% endif %}
					</ul>
					{% if user.officer.is_level_2 %}
					{% else %}
					<li  data-toggle="collapse" data-target="#case" class="collapsed {% block active-case %}{% endblock %}">
					  <a href="#"><i class="fa fa-file fa-lg"></i> Case <span class="arrow"></span></a>
					</li>
					<ul class="sub-menu collapse" id="case">

						<li class="{% block active-file-fir %}{% endblock %}"><a href="{% url 'cdms:fir_form' %}">File a FIR</a></li>

						<li class="{% block active-case-list %}{% endblock %}"><a href="{% url 'cdms:case_list' %}">Case List</a></li>
						
					</ul>
					
					<li class="{% block active-gd-list %}{% endblock %}">
					  <a href="{% url 'cdms:gd_list' %}">
					  <i class="fa fa-envelope fa-lg"></i> General Diary <span class="badge">{{ gd_number }}</span>
					  </a>
					</li>
					{% endif %}
				</ul>
			</div>
		</div>
</nav>
<div id="content-wrapper">
{% block body %}
{% endblock %}
</div>
{% block forJS %}
{% endblock %}
</body>
</html>

cdms/templates/cdms/gd_details.html
{% extends 'cdms/base.html' %}
{% block title %}GD details{% endblock %}
{% load my_filters %}
{% block active-gd-list %}active{% endblock %}


{% block body %}
<div class="container-fluid">
	<div class="row details-action-btn-row">
		<div  class="col-lg-offset-8 col-lg-4">
			<div class="btn-group pull-right">
				<a class="btn btn-default" href="{% url 'cdms:gd_list' %}" role="button">Back to the list</a>
				<a class="btn btn-success" href="#" role="button">Create a new case</a>
			</div>
		</div>
	</div>	
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-body">		
				<div  class="col-lg-6 col-xs-6">
					<address>
					  Name : <strong>{{ gd.name }}</strong><br>
					  National ID : {{ gd.national_id }}<br>
					  Father's Name : {{ gd.father_name }}<br>
					  Mother's Name : {{ gd.mother_name }}<br>
					</address>
				</div>
				<div  class="col-lg-6 col-xs-6">
					<address>
					  Date : <strong>{{ gd.date_time }}</strong><br>
					  Present Address : {{ gd.present_address }}<br>
					  permanent Address : {{ gd.permanent_address }}<br>
					  Mobile : <strong>{{ gd.mobile }}</strong>, Email : <strong>{{ gd.email }}</strong><br>
					</address>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-body">		
				<div  class="col-lg-11 col-xs-11">
					<h4>Deatils: </h4>
					<p>
						{{ gd.description|linebreaks }}
					</p>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		{% for files in gd.gd_files_set.all %}
			<div class="col-xs-4 col-md-2 ">
				<div class="file-show-div">
					<h4 class="text-center"><strong>{{ files.file.name|getExtension }}</strong></h4>
					<a href="{{ files.file.url }}" class="btn btn-success btn-sm margin-left-download-btn pull-right" target="_blank">
						<i class="fa fa-download"></i>
					</a>
				</div>
				<span class="fileNameCss text-info">{{ files.file.name|fileNameFiltering }}</span>
			</div>
			{% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
		{% endfor %}
	</div><br/>
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-body">
				<div  class="col-lg-6 col-xs-6">
					<h4>Assigned By: </h4>
					<h3>{{ gd.assigned_by.get_full_name }}</h3>
					<h5>{{ gd.assigned_by.officer.get_rank_display }} - {{ gd.assigned_by.officer.position }}</h5>
				</div>
				<div  class="col-lg-6 col-xs-6">
					<h4>Action Officer: </h4>
				{% if gd.action_officer %}
					<h3>{{ gd.action_officer.get_full_name }}</h3>
					<h5>{{ gd.action_officer.officer.get_rank_display }} - {{ gd.action_officer.officer.position }}</h5>
					{% if user.officer.is_level_3 %}
						<a class="btn btn-danger btn-sm" href="{% url 'cdms:remove_action_officer' gd.id %}" role="button">Remove this action officer</a>
					{% endif %}
				{% else %}
					{% if user.officer.is_level_3 %}
						<a class="btn btn-success" href="{% url 'cdms:assign_action_officer' gd.id %}" role="button">Assign an officer to take action</a>
					{% endif %}
				{% endif %}
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="panel panel-default">
			<div class="panel-body">
				<div  class="col-lg-11 col-xs-11">
					<h4>Action Deatils: </h4>
					{% if gd.action_details %}
						<p>{{ gd.action_details|linebreaks }}</p>
						<a class="btn btn-warning" href="{% url 'cdms:gd_action' gd.id %}" role="button">Edit</a>
					{% else %}
						<p>No action has been taken yet.</p>
						<a class="btn btn-success" href="{% url 'cdms:gd_action' gd.id %}" role="button">Take action</a>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

cdms/templates/cdms/thana_list.html
{% extends 'cdms/base.html' %}
{% block title %}Thana List{% endblock %}
{% block active-thana %}active{% endblock %}
{% block active-thana-list %}active{% endblock %}
{% load my_filters %}

{% block body %}
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-6">
			<h4><u>Thana List:</u></h4>
		</div>
		<div class="col-lg-6">
			<form class="form-inline pull-right" role="search" action="{% url 'cdms:thana_list' %}" method="get">
				<div class="form-group">
					<label for="id_district">District :</label>
					<select class="form-control" id="id_district" name="q">
						<option value="" selected="selected">---------</option>
					{% for district in districts %}
						<option value="{{ district.id }}" {% if request.GET.q %} {{ district.id|isSelected:request.GET.q }} {% endif %} >{{ district.name }}</option>
					{% endfor %}
					</select>
				</div>
					<button type="submit" class="btn btn-success">Show</button>
			</form>
		</div>
	</div>	
	<div class="row">
		<div class="col-lg-12">
			<table class="table table-hover gd-table">
			    <thead>
					<tr>
						<th>#</th>
						<th>Name</th> 
					</tr>
				</thead>
				<tbody>
				{% if thanas %}
					{% for thana in thanas %}
						
						<tr onclick="window.document.location='{% url 'cdms:thana_details' thana.id %}'" class="">
							<td>{{ forloop.counter }}</td>
							<td>{{ thana.name }}</td>					
						</tr>  
						
					{% endfor %}
				{% endif %}
				</tbody>
            </table>
		</div>

	</div>



{% endblock %}